<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Command line suite" duration-ms="5051" started-at="2020-02-26T17:34:12 ICT" finished-at="2020-02-26T17:34:17 ICT">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="5051" started-at="2020-02-26T17:34:12 ICT" finished-at="2020-02-26T17:34:17 ICT">
      <class name="actions.TestAPI">
        <test-method status="PASS" signature="Setup()[pri:0, instance:actions.TestAPI@16c0663d]" name="Setup" is-config="true" duration-ms="444" started-at="2020-02-26T17:34:12 ICT" finished-at="2020-02-26T17:34:12 ICT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Setup -->
        <test-method status="PASS" signature="testErrorCases(java.lang.String, java.lang.String)[pri:0, instance:actions.TestAPI@16c0663d]" name="testErrorCases" duration-ms="1554" started-at="2020-02-26T17:34:12 ICT" data-provider="ErrorCases" finished-at="2020-02-26T17:34:14 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[40000007600000]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[invalid_request_error]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testErrorCases -->
        <test-method status="PASS" signature="testNegativeCases(java.lang.String, java.lang.String)[pri:0, instance:actions.TestAPI@16c0663d]" name="testNegativeCases" duration-ms="569" started-at="2020-02-26T17:34:14 ICT" data-provider="NegativeCases" finished-at="2020-02-26T17:34:14 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[4000000000009979]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[stolen_card]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNegativeCases -->
        <test-method status="FAIL" signature="testNegativeCases(java.lang.String, java.lang.String)[pri:0, instance:actions.TestAPI@16c0663d]" name="testNegativeCases" duration-ms="615" started-at="2020-02-26T17:34:14 ICT" data-provider="NegativeCases" finished-at="2020-02-26T17:34:15 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[4000000000009995]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[insufficient_funds]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [201] but found [400]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [201] but found [400]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at actions.TestAPI.testNegativeCases(TestAPI.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at actions.TestRunner.main(TestRunner.java:11)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNegativeCases -->
        <test-method status="PASS" signature="testNegativeCases(java.lang.String, java.lang.String)[pri:0, instance:actions.TestAPI@16c0663d]" name="testNegativeCases" duration-ms="614" started-at="2020-02-26T17:34:15 ICT" data-provider="NegativeCases" finished-at="2020-02-26T17:34:16 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[4000000000009987]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[lost_card]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNegativeCases -->
        <test-method status="PASS" signature="testPositiveCases(java.lang.String, java.lang.String)[pri:0, instance:actions.TestAPI@16c0663d]" name="testPositiveCases" duration-ms="616" started-at="2020-02-26T17:34:16 ICT" data-provider="PositiveCases" finished-at="2020-02-26T17:34:16 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[4100000000000019]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[blocked]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPositiveCases -->
        <test-method status="PASS" signature="testPositiveCases(java.lang.String, java.lang.String)[pri:0, instance:actions.TestAPI@16c0663d]" name="testPositiveCases" duration-ms="610" started-at="2020-02-26T17:34:16 ICT" data-provider="PositiveCases" finished-at="2020-02-26T17:34:17 ICT">
          <params>
            <param index="0">
              <value>
                <![CDATA[4242424242424242]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[succeeded]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPositiveCases -->
      </class> <!-- actions.TestAPI -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
